version: "3.8"
services:
  postgres:
    container_name: matrix_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      #Default super user
      POSTGRES_USER: neo
      #Super user password
      POSTGRES_PASSWORD: trinity@123
      #Database name
      POSTGRES_DB: data_matrix
      #Timezone of Asia/Kolkata
      TZ: UTC
    volumes:
      # Named volume
      - postgres-volume:/postgres/data
      # User-relative path
      - ~/tmp:/etc/postgres/data:ro
  batch_mysql:
    container_name: matrix_mysql_instance_1
    image: mysql
    ports:
      - 3306:3306
    environment:
      #Default root password
      MYSQL_ROOT_PASSWORD: Welcome@123
      MYSQL_USER: neo
      #Super user password
      MYSQL_PASSWORD: trinity@123
      #Database name
      MYSQL_DATABASE: data_matrix
      TZ: UTC
    volumes:
      # Named volume
      - batch_mysql-volume:/mysql/data
  sentinel_mysql:
    container_name: matrix_mysql_instance_2
    image: mysql
    ports:
      - 3308:3306
    environment:
      #Default root password
      MYSQL_ROOT_PASSWORD: Welcome@123
      MYSQL_USER: neo
      #Super user password
      MYSQL_PASSWORD: morpheus@123
      #Database name
      MYSQL_DATABASE: sentinel
      TZ: UTC
    volumes:
      # Named volume
      - sentinel_mysql-volume:/mysql/data

volumes:
  postgres-volume:
    driver: local
    external: false
  batch_mysql-volume:
    driver: local
    external: false
  sentinel_mysql-volume:
    driver: local
    external: false