version: "3.5"
services:
  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: docker-machine ip docker-machine active
      ADVERTISED_PORT: 9092