# ===================================================================
# COMMON SPRING BOOT PROPERTIES
#               
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

logging:
  config: classpath:log4j2.xml
  level:
    root: WARN
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        web: DEBUG


# ----------------------------------------
# IDENTITY (ContextIdApplicationContextInitializer)
# ----------------------------------------

spring:
  application:
    name: Data-Matrix
    admin:
      enable: true
  banner:
    charset: UTF-8
    location: classpath:banner.txt
    image:
      margin: 3.0
      width: 90.0

  # ----------------------------------------
  # ENVIRONMENT (dev/prod)
  # modify here to switch between environments
  # ----------------------------------------

  profiles:
    active: @activeProfile@

  # ----------------------------------------
  # JMX
  # ----------------------------------------

  jmx:
    default-domain: data-matrix

  # ----------------------------------------
  # EHCache
  # ----------------------------------------

  cache:
    jcache:
      config: classpath:ehcache.xml

  # ----------------------------------------
  # JACKSON CONFIGURATION
  # ----------------------------------------

  jackson:
    #This does no work with LocalDateTime/LocalDate - Need to use JSONConfiguration
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

  # ----------------------------------------
  # Application
  # ----------------------------------------
retry:
  delay: 5000


  # ----------------------------------------
  # ACTUATOR
  # ----------------------------------------

management:
  auditevents:
    enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
      threshold: 10MB
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"